image:
  file: gitpod.Dockerfile
ports:
  - port: 5432
    onOpen: ignore
  - port: 3000
    onOpen: open-preview
  - port: 6379
    onOpen: ignore
tasks:
  - name: "Redis server"
    command: redis-server
  - name: "Rails server"
    init: yarn install && yarn build && bin/setup && bundle exec rake assets:precompile
    command: bin/rails server -b 0.0.0.0
